#
#   install.yml
#
# derived from common/install-generic.yml
#Wed Oct 16 03:56:27 PM CEST 2024
---
#   <p> Variables
#   global_install_folder
#   users

#
#   <p> establish facts
#
- name: "[install] Definitions {Level: 5}"
  include_tasks: common-definitions.yml

#
#   <p> host-wide installation
#

#   <p> architecture specific installs
#   <N> perform first as dirs/files might depend on packages installed here
- { stat: { path: "{{ global_install_folder }}/arch:{{ hostcombo }}" }, delegate_to: localhost, register: igh }
- name: "[install.yml] folder={{ igh.stat.path | default('not found') }}"
  include_tasks: task-taskFolder.yml
  #apply: { tags: [ generic_igh ] }
  vars: { path: "{{ global_install_folder }}/arch:{{ hostcombo }}", install_user: root }
  tags: [ generic_igh ]
  when: igh.stat.exists

#   <p> all hosts
# detect folder
# seperate set_fact as register always overwrites variable
- { stat: { path: "{{ global_install_folder }}/host:*/host" }, delegate_to: localhost, register: iggRaw }
- { set_fact: { igg: "{{ iggRaw }}" } }
- { stat: { path: "{{ global_install_folder }}/host:*" }, delegate_to: localhost, register: iggRaw }
- { set_fact: { igg: "{{ iggRaw }}" }, when: not igg.stat.exists }
#- { stat: { path: "{{ global_install_folder }}/host:*" }, delegate_to: localhost, register: igg }
# process taskFolder
#- debug: { msg: "path={{ igg.stat.path }}" }
- name: "[install] folder={{ igg.stat.path | default('not found') }}"
  include_tasks: task-taskFolder.yml
  #apply: { tags: [ generic_igg ] }
  vars: { path: "{{ igg.stat.path }}", install_user: root, template_vars: "{{ features[inventory_hostname]['template_vars'] | default( {} ) }}" }
  tags: [ generic_igg ]
  #when: "not igg.stat.exists"
  when: igg.stat.exists

#   <p> current host
# detect folder
- { stat: { path: "{{ global_install_folder }}/host:{{ inventory_hostname }}/host" }, delegate_to: localhost, register: igfRaw }
- { set_fact: { igf: "{{ igfRaw }}" } }
- { stat: { path: "{{ global_install_folder }}/host:{{ inventory_hostname }}" }, delegate_to: localhost, register: igfRaw }
- { set_fact: { igf: "{{ igfRaw }}" }, when: not igf.stat.exists }
#- { stat: { path: "{{ global_install_folder }}/host:{{ inventory_hostname }}/host" }, delegate_to: localhost, register: igf }
- debug: { msg: "[install.yml:current_host:detect]: folder1st={{ global_install_folder }}/host:{{ inventory_hostname }}/host igf={{ igf }} stat={{ igfRaw }}"}
# process taskFolder
- name: "[install] folder={{ igf.stat.path | default('not found') }}"
  include_tasks: task-taskFolder.yml
  #apply: { tags: [ generic_igf ] }
  vars: { path: "{{ igf.stat.path }}", install_user: root, template_vars: "{{ features[inventory_hostname]['template_vars'] | default( {} ) }}" }
  tags: [ generic_igf ]
  when: igf.stat.exists

#
#   <p> user installation
#

- name: "[install] users"
  include_tasks: install-user.yml
  loop: "{{ users | default( [] ) }}"
  loop_control: { loop_var: user }
  tags: [ ig_user ]
