#
#   add-repo-'openSUSE Leap'.yml
#Fri Sep 25 22:58:47 CEST 2020
---


#   vars:
#       path

- include_tasks: common-pathDecompose.yml

- name: "[task-repo:openSUSE Leap] name={{ repo_name }}"
  zypper_repository:
    #name: "{{ repo_name }}"    # assume name defined through uri
    enabled: "{{ repo_enabled }}"
    priority: "{{ repo_prio }}"
    repo: "{{ uri }}"
    autorefresh: "{{ repo_autorefresh }}"
    overwrite_multiple: yes
    state: present
    auto_import_keys: "{{ repo_autoimport }}"
    runrefresh: yes
  vars:
    uri: "{{ lookup('file', '{{ path_src }}') | regex_replace('\\${releasever}', os_version) }}"
